version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432
    volumes:
      - postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080

volumes:
  postgresql:
